// app/layout.tsx
import type { Metadata } from 'next';
import './globals.css';
import { Inter, Poppins } from 'next/font/google';

import Navbar from '../../components/navbar/navbar';
import Footer from '../../components/footer/Footer';
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ['latin'] });
const poppins = Poppins({ subsets: ['latin'], weight: ['400', '600', '700'] });

export const metadata: Metadata = {
  title: 'Travel project',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={`${inter.className} ${poppins.className} min-h-screen flex flex-col`}>
        <Navbar />

        <main className='flex-1 mt-[56px]'>{children}</main>
        <Toaster />

        <Footer />
      </body>
    </html>
  );
}
